 # Use the official Nginx image as base
FROM nginx:alpine

# Copy the HTML file into the Nginx HTML directory
COPY index.html /usr/share/nginx/html

# Expose port 3000 to the outside world
EXPOSE 3000
